Replace podcast icon with Amazon logo
opensourcestories/opensourcestories.org pull request #117
Opened 2023-11-25 13:08 UTC by WebSnke

As mentioned in #108.

2023-12-08 10:25 UTC, WebSnke commented
@juliaferraioli @amcasari @perriefidelis 
Could one of you take a look at my pull request? Thanks.

2023-12-10 02:10 UTC, juliaferraioli requested changes
Thanks for pinging the issue -- I didn't get notified of your PR for some reason. I'll look into that.

2023-12-10 02:10 UTC, juliaferraioli commented on layouts/partials/svg/amazon.svg
Looking great! Can you please update the SVG to use this in the opening SVG tag? That lets it scale properly.

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" {{ with .size }} height="{{ . }}" {{ end }} >`

2023-12-10 08:59 UTC, WebSnke commented on layouts/partials/svg/amazon.svg
I just did and the SVG does not show up properly anymore...

2023-12-10 22:39 UTC, juliaferraioli approved these changes
Looks great! If you take the pr out of draft mode I can merge it.

@all-contributors, please add @WebSnke for coding contributions!

2023-12-10 22:39 UTC, juliaferraioli commented on layouts/partials/svg/amazon.svg
But it works great! It's the magic of hugo templates. I probably should change it eventually but it's not a high priority right now.

2023-12-10 22:40 UTC, juliaferraioli commented on layouts/partials/svg/amazon.svg
Oh, I triggered the deploy preview, so you can see it rendering: https://deploy-preview-117--opensourcestories.netlify.app/

2023-12-11 16:32 UTC, merged

2023-12-11 16:32 UTC, juliaferraioli commented
Let's try this again...

@all-contributors, please add @WebSnke for coding contributions!