#89 [REQUEST] Add fields for facilitator and editor to the story archetype
opensourcestories/opensourcestories.org pull request #93
Opened 2023-06-09 18:09 UTC by LuvvAggarwal

Solution Description:
Added "editor" property in stories.md archetype and created "credits.html" partial for templated with conditional rendering
Finally calling "credits" template in "single.html"
SS of final result
<img width="611" alt="image" src="https://github.com/opensourcestories/opensourcestories.org/assets/67058817/4da1cbe3-c7e1-482b-8442-b7964f065c72">

2023-06-09 23:41 UTC, juliaferraioli requested changes
Thanks so much! This is looking great. Added some comments to the files.

However, I think you accidentally committed more files thank you intended to. Mind removing the `.vs` folder from the PR?

2023-06-09 23:41 UTC, juliaferraioli commented on archetypes/stories.md
perfect, thanks!

2023-06-09 23:41 UTC, juliaferraioli commented on content/stories/2023/thea-flowers.md
This should be "Claire Moss", not "Clarie Moss".

2023-06-09 23:41 UTC, juliaferraioli commented on layouts/partials/credits.html
Could we add a period at the end of the sentence?

2023-06-09 23:41 UTC, juliaferraioli commented on layouts/stories/single.html
Just for cleanliness of the code, could you only add in line 48?

2023-06-10 03:12 UTC, LuvvAggarwal commented on layouts/stories/single.html
Sure, would make the necessary changes

2023-06-10 19:34 UTC, juliaferraioli requested changes

2023-06-10 19:34 UTC, juliaferraioli commented on layouts/stories/single.html
I'm sorry, I think I communicated that poorly! Your approach of creating a new partial was great. Let's stick with that.

I was referencing the fact that it seems like you modified the indentation for lines that you didn't change, so the diff reflected changes on lines without material changes. No worries though, if you can just add back the partial, we can resolve formatting later.

2023-06-10 19:34 UTC, juliaferraioli commented on .gitignore
Thanks so much for adding these!

2023-06-11 11:38 UTC, LuvvAggarwal commented on layouts/stories/single.html
Created a new partial and calling it in single.html

2023-06-12 14:43 UTC, juliaferraioli approved these changes
Thanks! This looks great!

2023-06-12 14:49 UTC, merged